spring:
  config:
    import: optional:classpath:local.env[.properties]

  application:
    name: restaurant-food-ordering-system

  profiles:
    default: loc
    group:
      loc: 'common, security, loc, flyway'
      dev: 'common, security, dev, flyway'