spring:
  config:
    activate:
      on-profile: common

  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        default_batch_fetch_size: 1000

  jackson:
    time-zone: UTC
    date-format: yyyy-MM-dd HH:mm:ss
    mapper:
      use-annotations: true
    visibility:
      field: any

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:dmnw emjx fqsu eyyi}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: false

jwt:
  access-token-expiry: 3600000      # 1 hour in milliseconds
  refresh-token-expiry: 604800000   # 7 days in milliseconds

app:
  cors:
    allowed-origins:
      - "*"
